version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - echo Entered the install phase...
      - curl -L https://convox.com/cli/linux/convox -o /tmp/convox
      - mv /tmp/convox /usr/local/bin/convox
      - chmod 755 /usr/local/bin/convox 
      - convox login console.convox.com -p 229d0768-4f06-4c04-b914-f2497bd8295b  
      - convox switch personal/demo-deserve-poc      
      
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...

    finally:
      - echo This always runs even if the login command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - release_id=$(convox build -a poc-app -m convox.yml --id)
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`      
      - convox run web ls -a poc-app --release $release_id
      - convox releases promote $release_id -a poc-app

