web:
  build: .
  cpu_shares: 10
  mem_limit: 512MB
  labels:
    - convox.port.443.protocol=tls
  links:
    - database
  ports:
    - 80:30000
    - 443:30000

database:
  image: convox/postgres
  labels:
    - convox.health.timeout=60
  ports:
    - 5432
  volumes:
    - /var/lib/postgresql/data
